backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "programs"
    label: "Program Belajar"
    folder: "content/programs"
    create: true
    extension: "json" # Biar output filenya .json
    format: "json"
    slug: "{{title}}"
    fields:
      - {label: "Judul Program", name: "title", widget: "string"}
      - {label: "Deskripsi Singkat", name: "description", widget: "text"}
      - {label: "Harga/Infaq", name: "price", widget: "string", default: "Gratis"}
      - {label: "Gambar (Optional)", name: "image", widget: "image", required: false}

  - name: "trainers"
    label: "Tim Mentor"
    folder: "content/trainers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nama & Gelar", name: "title", widget: "string"}
      - {label: "Foto Profil", name: "image", widget: "image"}
      - {label: "List Prestasi & Sanad", name: "body", widget: "markdown"}